name: Arena
main: AndreasHGK\Arena\Arena
version: 1.0.0-alpha1
api: 3.5.5
load: POSTWORLD
author: AndreasHGK
description: A PMMP arena plugin

permissions:
 arena:
  default: op
  description: "Arena root permission node"
  children:
   arena.command:
    default: true
    description: "gives access to /arena"
   arena.play:
    default: true
    description: "allows playing in arenas"
   arena.create:
    default: false
    description: "allows creation of arenas"