name: Arena
main: AndreasHGK\Arena\Arena
version: 1.0.0
api: 3.5.5
load: POSTWORLD
author: AndreasHGK
description: A PMMP arena plugin

permissions:
 arena:
  default: op
  description: "Arena root permission node"
  children:
   arena.command:
    default: true
    description: "gives permission to do /arena"
   arena.play:
    default: true
    description: "allows playing in arenas"
   arena.create:
    default: false
    description: "allows creation of arenas"
   arena.skip:
    default: false
    description: "skip arena timer"
   arena.admin:
    default: op
    description: "admin commands"
   claim.command:
    default: true
    description: "gives permission to do /claim"
   claim.use:
    default: false
    description: "allows the (un)claiming of land"
   claim.trust:
    default: false
    description: "allows trusting/untrusting players"
   adminmode:
    default: op
    description: "go into admin mode"
   arena.server:
    default: true
    description: "transfer to another server"
   arena.spawn:
    default: true
    description: "teleport to spawn"
   arena.wild:
    default: true
    description: "go to wild"