#     ╔═══╗╔═══╗╔═══╗╔═╗─╔╗╔═══╗
#    ║╔═╗║║╔═╗║║╔══╝║║╚╗║║║╔═╗║
#   ║║─║║║╚═╝║║╚══╗║╔╗╚╝║║║─║║
#  ║╚═╝║║╔╗╔╝║╔══╝║║╚╗║║║╚═╝║
# ║╔═╗║║║║╚╗║╚══╗║║─║║║║╔═╗║
#╚╝─╚╝╚╝╚═╝╚═══╝╚╝─╚═╝╚╝─╚╝

#default world for arenas.
world: "arenas"