#     ╔═══╗╔═══╗╔═══╗╔═╗─╔╗╔═══╗
#    ║╔═╗║║╔═╗║║╔══╝║║╚╗║║║╔═╗║
#   ║║─║║║╚═╝║║╚══╗║╔╗╚╝║║║─║║
#  ║╚═╝║║╔╗╔╝║╔══╝║║╚╗║║║╚═╝║
# ║╔═╗║║║║╚╗║╚══╗║║─║║║║╔═╗║
#╚╝─╚╝╚╝╚═╝╚═══╝╚╝─╚═╝╚╝─╚╝

#default world for arenas.
world: "arenas"

#commands to block while player is has joined an arena
blockcommands:
  - "/gamemode"
  - "/kill"
  - "/feed"
  - "/heal"
  - "/give"
  - "/teleport"
  - "/tp"
  - "/kit"
  - "/invis"
  - "/vanish"
  - "/spawn"
  - "/warp"
  - "/hub"

claims: true
healthtags: true